### ISSUE TITLE
Ship LSL lib w/ repo?

### ISSUE THREAD

**Issue by marionleborgne** [urish/muse-lsl#1]
`pylsl` ships the LSL c lib with the python package. This way when people `pip install` pylsl, they don't have to worry about installing this dep. Maybe this is something you are interested in doing if you decide to create this JS lsl lib that i was mentioning here: https://github.com/NeuroJS/eeg-stream-data-model/issues/1#issuecomment-310536236

See: https://github.com/chkothe/pylsl

**Comment by urish** [comment]
Thanks Marion, I will look into this!

**Comment by urish** [comment]
here we go: 

https://www.npmjs.com/package/node-lsl

**Comment by marionleborgne** [comment]
Very nice 👍
