### ISSUE TITLE
Which node version?

### ISSUE THREAD

**Issue by jdpigeon** [urish/muse-lsl#2]
I'm getting an error trying to run this:
```
async function connect() {
      ^^^^^^^^
SyntaxError: Unexpected token function
```
This seems to be related to me using Node v6.11 rather than >7

Is there a version you would recommend using? I'm considering using this library as part of a BCI workshop and want to know what to recommend everybody to install

**Comment by urish** [comment]
Nice to meet you :)

Yes, Node v7.6.0 or newer is needed.

Where will you be holding the workshop?

**Comment by jdpigeon** [comment]
Hey Urish! This is dano from neurotechx and SequencedC from Twitter.

Thanks for answering, I just wanted to be sure before experimenting with new Node versions.

The workshop will be in Toronto on September 5th. We'd like to use it to introduce people to basic neurohacking with Muse.

I'm developing the lesson here: https://github.com/jdpigeon/bci-workshop

**Comment by urish** [comment]
Very nice! Are you adapting the workshop for the 2016 Muse edition?

**Comment by jdpigeon** [comment]
Yup, the goal is to update for the new Muse, get it runnable on all platforms, and update the lesson content a bit

**Comment by urish** [comment]
Sounds great! I'd love to hear from you how it goes :)
